import type {
  SkillCategory,
  TechnologyItem,
  ExperienceItem,
  ProjectItem,
  TestimonialItem,
  CertificationItem,
  BlogPost,
  ToolItem,
} from "./types"

export const skills: SkillCategory[] = [
  {
    category: "Frontend Development",
    items: [
      { name: "React / Next.js", level: 95 },
      { name: "TypeScript", level: 90 },
      { name: "Tailwind CSS", level: 85 },
      { name: "Vue.js", level: 75 },
    ],
  },
  {
    category: "Backend Development",
    items: [
      { name: "Node.js", level: 90 },
      { name: "Python", level: 85 },
      { name: "PostgreSQL", level: 80 },
      { name: "REST / GraphQL", level: 85 },
    ],
  },
  {
    category: "Cloud & DevOps",
    items: [
      { name: "AWS", level: 85 },
      { name: "Docker / Kubernetes", level: 80 },
      { name: "CI/CD", level: 85 },
      { name: "Observability", level: 75 },
    ],
  },
  {
    category: "Leadership & Soft Skills",
    items: [
      { name: "Team Leadership", level: 90 },
      { name: "System Architecture", level: 85 },
      { name: "Code Review", level: 95 },
      { name: "Mentoring", level: 85 },
    ],
  },
]

export const technologies: TechnologyItem[] = [
  {
    name: "React",
    category: "Frontend",
    years: 5,
    yearsLabel: "5+ years",
    description: "Building scalable user interfaces with modern React patterns, hooks, and state management.",
    icon: "/logos/react.png",
  },
  {
    name: "Next.js",
    category: "Frontend",
    years: 4,
    yearsLabel: "4+ years",
    description: "Full-stack React framework for production-grade applications with SSR and API routes.",
    icon: "/logos/nextjs.png",
  },
  {
    name: "TypeScript",
    category: "Frontend",
    years: 4,
    yearsLabel: "4+ years",
    description: "Type-safe JavaScript development for better code quality and developer experience.",
    icon: "/logos/typescript.png",
  },
  {
    name: "Node.js",
    category: "Backend",
    years: 6,
    yearsLabel: "6+ years",
    description: "Server-side JavaScript runtime for building scalable network applications.",
    icon: "/logos/node.png",
  },
  {
    name: "PostgreSQL",
    category: "Database",
    years: 5,
    yearsLabel: "5+ years",
    description: "Advanced relational database management with complex queries and optimization.",
    icon: "/logos/postgres.png",
  },
  {
    name: "AWS",
    category: "Cloud",
    years: 4,
    yearsLabel: "4+ years",
    description: "Cloud infrastructure, serverless computing, and managed services at scale.",
    icon: "/logos/aws.png",
  },
  {
    name: "Docker",
    category: "DevOps",
    years: 4,
    yearsLabel: "4+ years",
    description: "Containerization and orchestration for consistent deployment environments.",
    icon: "/logos/docker.png",
  },
  {
    name: "GraphQL",
    category: "Backend",
    years: 3,
    yearsLabel: "3+ years",
    description: "Query language for APIs providing efficient data fetching and type safety.",
    icon: "/logos/graphql.png",
  },
]

export const tools: ToolItem[] = [
  {
    name: "VS Code",
    category: "Development",
    description: "Primary code editor with extensive customization and plugin ecosystem for maximum productivity.",
    logoSrc: "/logos/tools/vscode.png",
    proficiency: "Expert",
    yearsUsed: 6,
  },
  {
    name: "GitHub",
    category: "Development",
    description: "Version control and collaboration platform for seamless code management and team workflows.",
    logoSrc: "/logos/github.png",
    proficiency: "Expert",
    yearsUsed: 7,
  },
  {
    name: "Postman",
    category: "Development",
    description: "Comprehensive API development and testing platform for REST and GraphQL endpoints.",
    logoSrc: "/logos/tools/postman.png",
    proficiency: "Advanced",
    yearsUsed: 5,
  },
  {
    name: "React",
    category: "Development",
    description: "Component-based library for building dynamic and scalable user interfaces.",
    logoSrc: "/logos/react.png",
    proficiency: "Expert",
    yearsUsed: 5,
  },
  {
    name: "Next.js",
    category: "Development",
    description: "Full-stack React framework with server-side rendering and API route capabilities.",
    logoSrc: "/logos/nextjs.png",
    proficiency: "Expert",
    yearsUsed: 4,
  },
  {
    name: "TypeScript",
    category: "Development",
    description: "Typed superset of JavaScript providing enhanced developer experience and code reliability.",
    logoSrc: "/logos/typescript.png",
    proficiency: "Expert",
    yearsUsed: 4,
  },
  {
    name: "Node.js",
    category: "Development",
    description: "JavaScript runtime for building scalable server-side applications and APIs.",
    logoSrc: "/logos/node.png",
    proficiency: "Expert",
    yearsUsed: 6,
  },
  {
    name: "Python",
    category: "Development",
    description: "Versatile programming language for backend development, data analysis, and automation.",
    logoSrc: "/logos/python.png",
    proficiency: "Advanced",
    yearsUsed: 4,
  },
  {
    name: "Figma",
    category: "Design",
    description: "Collaborative design tool for creating stunning UI/UX designs and interactive prototypes.",
    logoSrc: "/logos/tools/figma.png",
    proficiency: "Advanced",
    yearsUsed: 4,
  },
  {
    name: "Framer",
    category: "Design",
    description: "Advanced prototyping tool for creating interactive web experiences and animations.",
    logoSrc: "/logos/tools/framer.png",
    proficiency: "Intermediate",
    yearsUsed: 2,
  },
  {
    name: "Docker",
    category: "DevOps",
    description: "Containerization platform ensuring consistent development and deployment environments.",
    logoSrc: "/logos/docker.png",
    proficiency: "Advanced",
    yearsUsed: 4,
  },
  {
    name: "Vercel",
    category: "DevOps",
    description: "Modern deployment platform with seamless Git integration and edge network optimization.",
    logoSrc: "/logos/vercel.png",
    proficiency: "Expert",
    yearsUsed: 4,
  },
  {
    name: "AWS",
    category: "DevOps",
    description: "Comprehensive cloud platform for scalable infrastructure and managed services.",
    logoSrc: "/logos/aws.png",
    proficiency: "Advanced",
    yearsUsed: 4,
  },
  {
    name: "Kubernetes",
    category: "DevOps",
    description: "Container orchestration platform for automating deployment and scaling of applications.",
    logoSrc: "/logos/kubernetes.png",
    proficiency: "Intermediate",
    yearsUsed: 2,
  },
  {
    name: "Slack",
    category: "Communication",
    description: "Team communication hub for seamless collaboration and project coordination.",
    logoSrc: "/logos/tools/slack.png",
    proficiency: "Expert",
    yearsUsed: 6,
  },
  {
    name: "Notion",
    category: "Productivity",
    description: "All-in-one workspace for documentation, project management, and knowledge organization.",
    logoSrc: "/logos/tools/notion.png",
    proficiency: "Advanced",
    yearsUsed: 3,
  },
  {
    name: "Linear",
    category: "Productivity",
    description: "Modern issue tracking and project management designed for high-performance development teams.",
    logoSrc: "/logos/tools/linear.png",
    proficiency: "Advanced",
    yearsUsed: 2,
  },
  {
    name: "Raycast",
    category: "Productivity",
    description: "Powerful launcher and productivity tool that streamlines macOS workflows and automation.",
    logoSrc: "/logos/tools/raycast.png",
    proficiency: "Advanced",
    yearsUsed: 2,
  },
  {
    name: "TablePlus",
    category: "Database",
    description: "Modern database management tool with intuitive GUI for multiple database systems.",
    logoSrc: "/logos/tools/tableplus.png",
    proficiency: "Advanced",
    yearsUsed: 3,
  },
  {
    name: "PostgreSQL",
    category: "Database",
    description: "Advanced open-source relational database with powerful features and performance optimization.",
    logoSrc: "/logos/postgres.png",
    proficiency: "Advanced",
    yearsUsed: 5,
  },
  {
    name: "MySQL",
    category: "Database",
    description: "Reliable relational database management system for web applications and data storage.",
    logoSrc: "/logos/mysql.png",
    proficiency: "Advanced",
    yearsUsed: 4,
  },
  {
    name: "MongoDB",
    category: "Database",
    description: "NoSQL document database for flexible data modeling and horizontal scaling.",
    logoSrc: "/logos/mongodb.png",
    proficiency: "Intermediate",
    yearsUsed: 3,
  },
  {
    name: "Redis",
    category: "Database",
    description: "In-memory data structure store for caching, session management, and real-time applications.",
    logoSrc: "/logos/redis.png",
    proficiency: "Intermediate",
    yearsUsed: 3,
  },
  {
    name: "GraphQL",
    category: "Development",
    description: "Query language and runtime for APIs providing efficient and flexible data fetching.",
    logoSrc: "/logos/graphql.png",
    proficiency: "Advanced",
    yearsUsed: 3,
  },
]

export const experience: ExperienceItem[] = [
  {
    company: "ACME FinTech",
    role: "Senior Full Stack Engineer",
    period: "2022 - Present",
    highlights: [
      "Led development of payment processing platform handling $50M+ monthly volume",
      "Reduced API response times by 60% through database optimization and caching",
      "Mentored 3 junior developers and established code review best practices",
      "Implemented comprehensive testing strategy increasing coverage to 95%",
    ],
    tech: ["React", "Node.js", "PostgreSQL", "AWS", "TypeScript"],
    logoSrc: "/images/companies/acme-fintech-logo.png",
  },
  {
    company: "HealthCore Systems",
    role: "Full Stack Developer",
    period: "2020 - 2022",
    highlights: [
      "Built HIPAA-compliant patient portal serving 100K+ users",
      "Integrated with 15+ healthcare APIs and EHR systems",
      "Improved application performance by 40% through code optimization",
      "Collaborated with medical professionals to design intuitive workflows",
    ],
    tech: ["Vue.js", "Python", "MySQL", "Docker", "Redis"],
    logoSrc: "/images/companies/healthcore-systems-logo.png",
  },
  {
    company: "SaaSify",
    role: "Frontend Developer",
    period: "2019 - 2020",
    highlights: [
      "Developed responsive dashboard for B2B analytics platform",
      "Implemented real-time data visualization with D3.js",
      "Reduced bundle size by 35% through code splitting and optimization",
      "Created component library used across 5+ product teams",
    ],
    tech: ["React", "JavaScript", "Sass", "Webpack", "Jest"],
    logoSrc: "/images/companies/saasify-logo.png",
  },
]

export const projects: ProjectItem[] = [
  {
    title: "Payments Platform",
    summary: "Enterprise payment processing system with real-time fraud detection",
    description:
      "A comprehensive payment platform built for high-volume transactions with advanced fraud detection, multi-currency support, and real-time analytics dashboard.",
    highlights: [
      "Processes $50M+ monthly transaction volume",
      "99.9% uptime with sub-200ms response times",
      "Advanced fraud detection reducing chargebacks by 40%",
      "Multi-currency support for 25+ countries",
    ],
    tags: ["React", "Node.js", "PostgreSQL", "Redis", "AWS"],
    results: "50M+ monthly volume",
    imageAlt: "Payment platform dashboard showing transaction analytics",
  },
  {
    title: "Care Portal",
    summary: "HIPAA-compliant patient management system for healthcare providers",
    description:
      "A secure healthcare platform enabling patient-provider communication, appointment scheduling, and medical record management with full HIPAA compliance.",
    highlights: [
      "Serves 100K+ active patients and providers",
      "HIPAA-compliant with end-to-end encryption",
      "Integrated with 15+ EHR systems",
      "Mobile-first responsive design",
    ],
    tags: ["Vue.js", "Python", "MySQL", "Docker", "HIPAA"],
    results: "100K+ users",
    imageAlt: "Healthcare portal interface showing patient dashboard",
  },
  {
    title: "Analytics SaaS",
    summary: "Real-time business intelligence platform with custom dashboards",
    description:
      "A powerful analytics platform providing real-time insights, custom dashboard creation, and automated reporting for enterprise clients.",
    highlights: [
      "Real-time data processing of 1M+ events/day",
      "Custom dashboard builder with drag-and-drop",
      "Automated report generation and scheduling",
      "API integrations with 50+ data sources",
    ],
    tags: ["React", "D3.js", "Node.js", "MongoDB", "Kafka"],
    results: "1M+ events/day",
    imageAlt: "Analytics dashboard showing real-time business metrics",
  },
]

export const testimonials: TestimonialItem[] = [
  {
    name: "Alex Johnson",
    title: "VP Engineering, Acme",
    quote: "A rare blend of technical depth and leadership. Drove platform modernization with outstanding results.",
    date: "May 10, 2024",
    avatarSrc: "/avatars/avatar-1.png",
  },
  {
    name: "Priya Singh",
    title: "Director of Product, HealthCore",
    quote: "Consistently delivers high-quality outcomes and collaborates across disciplines with clarity and empathy.",
    date: "Apr 29, 2024",
    avatarSrc: "/avatars/avatar-2.png",
  },
  {
    name: "Diego Martinez",
    title: "CTO, SaaSify",
    quote: "Transformed our engineering culture and shipped critical capabilities under tight deadlines.",
    date: "Mar 17, 2024",
    avatarSrc: "/avatars/avatar-3.png",
  },
  {
    name: "Isabella Rossi",
    title: "Content Strategist",
    quote:
      "The insights and delivery helped us make better, data-driven decisions. Highly recommend for content analysis.",
    date: "Sep 4, 2024",
    avatarSrc: "/avatars/avatar-4.png",
  },
]

export const certifications: CertificationItem[] = [
  {
    name: "AWS Solutions Architect Professional",
    organization: "Amazon Web Services",
    category: "Cloud",
    issueDate: "2023-03-15",
    expiryDate: "2026-03-15",
    credentialId: "AWS-SAP-2023-001234",
    verificationUrl: "https://aws.amazon.com/verification",
    description: "Advanced AWS architecture design, security, and cost optimization for enterprise-scale applications.",
    skills: ["AWS", "Cloud Architecture", "Security", "Cost Optimization"],
    badgeSrc: "/badges/aws-solutions-architect-professional.png",
    badgeAlt: "AWS Solutions Architect Professional badge",
  },
  {
    name: "Certified Kubernetes Administrator",
    organization: "Cloud Native Computing Foundation",
    category: "DevOps",
    issueDate: "2023-01-20",
    expiryDate: "2026-01-20",
    credentialId: "CKA-2023-567890",
    verificationUrl: "https://training.linuxfoundation.org/certification/verify",
    description: "Kubernetes cluster administration, troubleshooting, and application lifecycle management.",
    skills: ["Kubernetes", "Docker", "Container Orchestration", "DevOps"],
    badgeSrc: "/badges/kubernetes-administrator.png",
    badgeAlt: "Certified Kubernetes Administrator badge",
  },
  {
    name: "Google Professional Cloud Architect",
    organization: "Google Cloud",
    category: "Cloud",
    issueDate: "2022-11-10",
    expiryDate: "2024-11-10",
    credentialId: "GCP-PCA-2022-112233",
    verificationUrl: "https://cloud.google.com/certification/verify",
    description: "Design and manage robust, secure, scalable, and dynamic solutions on Google Cloud Platform.",
    skills: ["Google Cloud", "Architecture", "Security", "Scalability"],
    badgeSrc: "/badges/gcp-professional-cloud-architect.png",
    badgeAlt: "Google Professional Cloud Architect badge",
  },
  {
    name: "Certified Information Systems Security Professional",
    organization: "ISC2",
    category: "Security",
    issueDate: "2022-06-01",
    expiryDate: "2025-06-01",
    credentialId: "CISSP-445566",
    verificationUrl: "https://isc2.org/verify",
    description: "Advanced cybersecurity principles, risk management, and security architecture design.",
    skills: ["Cybersecurity", "Risk Management", "Security Architecture", "Compliance"],
    badgeSrc: "/badges/cissp.png",
    badgeAlt: "CISSP certification badge",
  },
  {
    name: "MongoDB Certified Developer",
    organization: "MongoDB Inc.",
    category: "Database",
    issueDate: "2023-08-15",
    expiryDate: "2026-08-15",
    credentialId: "MDB-DEV-778899",
    verificationUrl: "https://university.mongodb.com/verify",
    description: "Advanced MongoDB development, aggregation pipelines, and performance optimization.",
    skills: ["MongoDB", "NoSQL", "Database Design", "Performance Tuning"],
    badgeSrc: "/badges/mongodb-developer.png",
    badgeAlt: "MongoDB Certified Developer badge",
  },
  {
    name: "Certified ScrumMaster",
    organization: "Scrum Alliance",
    category: "Leadership",
    issueDate: "2021-09-30",
    expiryDate: "2023-09-30",
    credentialId: "CSM-001122",
    verificationUrl: "https://scrumalliance.org/verify",
    description: "Agile project management, team facilitation, and Scrum framework implementation.",
    skills: ["Scrum", "Agile", "Team Leadership", "Project Management"],
    badgeSrc: "/badges/certified-scrummaster.png",
    badgeAlt: "Certified ScrumMaster badge",
  },
]

export const posts: BlogPost[] = [
  {
    slug: "scaling-event-driven-architectures",
    title: "Scaling Event-Driven Architectures",
    excerpt: "Lessons from migrating synchronous services to an event-driven mesh.",
    date: "2025-07-10",
    tags: ["Architecture", "Kafka", "Scalability"],
    content:
      "Event-driven architectures unlock scalability and resilience.\nThis article covers patterns like outbox, idempotency, and schema evolution in practice.",
  },
  {
    slug: "measuring-developer-experience",
    title: "Measuring Developer Experience (DX)",
    excerpt: "How to quantify and improve DX for sustained velocity.",
    date: "2025-06-22",
    tags: ["DX", "Tooling", "Leadership"],
    content: "DX is a leading indicator of delivery. We discuss metrics, feedback loops, and pragmatic investments.",
  },
  {
    slug: "web-performance-core-web-vitals",
    title: "Web Performance and Core Web Vitals",
    excerpt: "Practical steps to improve LCP, CLS, and INP on modern stacks.",
    date: "2025-05-02",
    tags: ["Performance", "Next.js", "Frontend"],
    content:
      "Core Web Vitals directly impact user outcomes.\nWe explore image optimization, streaming, RSC, and prefetch strategies.",
  },
]
